[package]
name = "wyn-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
nom.workspace = true
polytype.workspace = true
spirv.workspace = true
log.workspace = true
rspirv = "0.12"
itertools = "0.14.0"
indexmap = "2.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
env_logger.workspace = true
naga = { version = "22.0", features = ["spv-in"] }
anyhow = "1.0"
